const MONTHS=['Janv.','Fév.','Mars','Avr.','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'];
const IMG=['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=75','https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=75','https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=75','https://images.unsplash.com/photo-1533240332313-0db49b459ad6?auto=format&fit=crop&w=900&q=75'];
const seedRaces=[
{id:'r1',name:'Trail des Forts',city:'Besançon',date:'2027-05-09',type:'trail',distance:30,elev:1150,index:'50K',lat:47.2378,lon:6.0241,open:'2026-11-15',img:IMG[1]},
{id:'r2',name:'Transju Trail',city:'Morez',date:'2027-06-06',type:'trail',distance:42,elev:2200,index:'50K',lat:46.522,lon:6.022,open:'2026-10-20',img:IMG[0]},
{id:'r3',name:'Trail du Mont d’Or',city:'Métabief',date:'2027-04-18',type:'trail',distance:25,elev:1350,index:'20K',lat:46.773,lon:6.351,open:'2026-12-01',img:IMG[2]},
{id:'r4',name:'Marathon du Mont-Blanc',city:'Chamonix',date:'2027-06-27',type:'trail',distance:42,elev:2540,index:'50K',lat:45.9237,lon:6.8694,open:'2026-10-15',img:IMG[1]},
{id:'r5',name:'10 km des Rives',city:'Genève',date:'2027-01-24',type:'road',distance:10,elev:60,index:'',lat:46.2044,lon:6.1432,open:'2026-09-20',img:IMG[3]},
{id:'r6',name:'Semi du Léman',city:'Lausanne',date:'2027-03-21',type:'road',distance:21.1,elev:180,index:'',lat:46.5197,lon:6.6323,open:'2026-11-02',img:IMG[3]},
{id:'r7',name:'Trail des Crêtes Jurassiennes',city:'Les Rousses',date:'2027-07-11',type:'trail',distance:34,elev:1650,index:'50K',lat:46.484,lon:6.063,open:'2027-01-12',img:IMG[0]},
{id:'r8',name:'Ultra des Lacs',city:'Annecy',date:'2027-09-12',type:'trail',distance:70,elev:4300,index:'100K',lat:45.8992,lon:6.1294,open:'2027-02-01',img:IMG[2]},
{id:'r9',name:'Course des Lumières',city:'Lyon',date:'2027-10-17',type:'road',distance:21.1,elev:150,index:'',lat:45.764,lon:4.8357,open:'2027-03-05',img:IMG[3]},
{id:'r10',name:'Sainté Trail Nocturne',city:'Saint-Étienne',date:'2027-12-05',type:'trail',distance:45,elev:1750,index:'',lat:45.4397,lon:4.3872,open:'2027-04-20',img:IMG[0]}
];
const defaults={year:2027,profile:{name:'',lat:null,lon:null,maxTravel:90,indexPref:'prefer'},goals:[{id:'g1',type:'10 km',month:0,min:8,max:12,window:'late',travel:75,index:'any',priority:'normal'},{id:'g2',type:'Trail',month:3,min:25,max:35,window:'mid',travel:120,index:'prefer',priority:'main'},{id:'g3',type:'Semi-marathon',month:9,min:20,max:23,window:'month',travel:120,index:'any',priority:'normal'}],following:['r3','r4'],registered:[],customRaces:[],feedback:[]};
let state=load();let filter='all';let activeMonth=new Date().getMonth();
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem('toposeason-beta')||'{}')}}catch(e){return structuredClone(defaults)}}
function save(){localStorage.setItem('toposeason-beta',JSON.stringify(state))}
function allRaces(){return [...seedRaces,...(state.customRaces||[])]}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function hav(a,b,c,d){const R=6371,p=Math.PI/180;const x=(c-a)*p,y=(d-b)*p;const q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function travel(r){if(state.profile.lat==null||r.lat==null)return null;const km=hav(state.profile.lat,state.profile.lon,r.lat,r.lon),road=km*1.23;return {km:Math.round(road),min:Math.max(15,Math.round((road/72)*60/5)*5)}}
function matchRace(r){let best=0;for(const g of state.goals){let s=0;const dm=Math.abs(new Date(r.date).getMonth()-Number(g.month));s+=dm===0?35:dm===1?15:0;const mid=(+g.min + +g.max)/2,delta=Math.abs(r.distance-mid);s+=Math.max(0,30-delta*2);const wantsTrail=/trail/i.test(g.type),isTrail=r.type==='trail';s+=wantsTrail===isTrail?15:3;if(g.index==='required')s+=r.index?15:-40;else if(g.index==='prefer'&&r.index)s+=10;const t=travel(r);if(t)s+=t.min<=+g.travel?10:Math.max(-15,10-(t.min-g.travel)/6);else s+=5;best=Math.max(best,Math.round(s))}return Math.max(1,Math.min(99,best))}
function openStatus(r){if(!r.open)return {c:'',txt:'Date inconnue'};const today=new Date(),d=new Date(r.open+'T10:00:00'),days=Math.ceil((d-today)/86400000);if(days<=0)return {c:'open',txt:'Inscriptions ouvertes'};if(days<=30)return {c:'soon',txt:'Ouverture dans '+days+' j'};return {c:'',txt:'Ouverture '+d.toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}}
function goalLabel(g){return g.type==='Trail'||g.type==='Ultra trail'?`${g.type} ${g.min}-${g.max} km`:g.type}
function renderMonths(){document.querySelector('#months').innerHTML=MONTHS.map((m,i)=>`<button class="month ${state.goals.some(g=>+g.month===i)?'has':''} ${i===activeMonth?'active':''}" data-month="${i}"><b>${m}</b><small>${state.year}</small></button>`).join('')}
function mainGoal(){return state.goals.find(g=>g.priority==='main')||state.goals[0]}
function renderHero(){const g=mainGoal();const h=document.querySelector('#hero');if(!g){h.innerHTML=`<span class="eyebrow">Ma saison ${state.year}</span><h1>Pose ton premier objectif.</h1><p>Choisis une période, une distance et ton rayon de déplacement.</p><button class="btn primary" data-add-goal>+ Ajouter un objectif</button>`;return}const rec=[...allRaces()].sort((a,b)=>matchRace(b)-matchRace(a)).find(r=>new Date(r.date).getMonth()===+g.month);h.innerHTML=`<span class="eyebrow">Objectif principal · ${MONTHS[g.month]} ${state.year}</span><h1>${esc(goalLabel(g))}</h1><p>${g.index==='required'?'UTMB Index obligatoire':g.index==='prefer'?'UTMB Index préféré':'Toutes les courses'} · ${g.travel} min de trajet max.</p><div class="hero-meta"><span class="glass">${g.min}-${g.max} km</span><span class="glass">${g.window==='late'?'Fin du mois':g.window==='early'?'Début du mois':g.window==='mid'?'Milieu du mois':'Mois complet'}</span>${rec?`<span class="glass">Meilleur match ${matchRace(rec)}%</span>`:''}</div><div class="hero-actions"><button class="btn primary" data-go="explore">Trouver ma course</button><button class="btn" style="background:rgba(255,255,255,.15);color:#fff" data-edit-goal="${g.id}">Modifier</button></div>`}
function card(r){const t=travel(r),s=matchRace(r),follow=state.following.includes(r.id);return `<article class="race-card" data-race="${r.id}"><div class="race-img" style="background-image:url('${r.img||IMG[1]}')"><span class="badge">${r.type==='trail'?'Trail':'Route'}</span></div><div class="race-body"><div>${r.index?`<span class="badge index">UTMB Index ${r.index}</span>`:''}</div><h3>${esc(r.name)}</h3><div class="sub">${esc(r.city)} · ${new Date(r.date+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}</div><div class="metrics"><span>↝ ${r.distance} km</span><span>△ ${r.elev} D+</span><span>🚗 ${t?t.min+' min':'Activer position'}</span></div><div class="match"><span class="score">${s}% match</span><button class="heart ${follow?'on':''}" data-follow="${r.id}" aria-label="Suivre">${follow?'♥':'♡'}</button></div></div></article>`}
function renderRecommended(){document.querySelector('#recommended').innerHTML=[...allRaces()].sort((a,b)=>matchRace(b)-matchRace(a)).slice(0,2).map(card).join('')}
function renderWatchPreview(){const rs=allRaces().filter(r=>state.following.includes(r.id)).sort((a,b)=>new Date(a.open||'2999')-new Date(b.open||'2999'));const e=document.querySelector('#watchPreview');if(!rs.length){e.innerHTML='<div class="empty">Ajoute une course à ta veille depuis Explorer.</div>';return}const r=rs[0],st=openStatus(r);e.innerHTML=`<div class="watch-preview" data-race="${r.id}"><div><span class="badge ${st.c}">${st.txt}</span><h3>${esc(r.name)}</h3><div class="sub">${esc(r.city)} · ${r.distance} km · ${r.elev} D+</div></div><b>›</b></div>`}
function renderSeason(){renderMonths();renderHero();renderRecommended();renderWatchPreview()}
function renderExplore(){const q=document.querySelector('#searchInput').value.toLowerCase().trim();let rs=allRaces().filter(r=>!q||(`${r.name} ${r.city} ${r.distance}`).toLowerCase().includes(q));if(filter==='trail')rs=rs.filter(r=>r.type==='trail');if(filter==='road')rs=rs.filter(r=>r.type==='road');if(filter==='index')rs=rs.filter(r=>r.index);if(filter==='near')rs=rs.filter(r=>{const t=travel(r);return t&&t.min<=state.profile.maxTravel});rs.sort((a,b)=>matchRace(b)-matchRace(a));document.querySelector('#raceList').innerHTML=rs.length?rs.map(r=>{const t=travel(r),s=matchRace(r),f=state.following.includes(r.id);return `<article class="list-card" data-race="${r.id}"><div class="thumb" style="background-image:url('${r.img||IMG[1]}')"></div><div><div class="small muted">${new Date(r.date+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}</div><h3>${esc(r.name)}</h3><div class="sub">${esc(r.city)} ${r.index?'· UTMB Index '+r.index:''}</div><div class="metrics"><span>${r.distance} km</span><span>${r.elev} D+</span><span>${t?t.min+' min':'Position ?'}</span><span class="score">${s}%</span></div></div><button class="heart ${f?'on':''}" data-follow="${r.id}">${f?'♥':'♡'}</button></article>`}).join(''):'<div class="empty">Aucune course ne correspond à ces filtres.</div>'}
function renderWatch(){const rs=allRaces().filter(r=>state.following.includes(r.id));document.querySelector('#watchList').innerHTML=rs.length?rs.map(r=>{const st=openStatus(r),reg=state.registered.includes(r.id);return `<div class="watch-row" data-race="${r.id}"><div><div class="status-group"><span class="badge ${st.c}">${st.txt}</span>${reg?'<span class="badge open">Inscrit ✓</span>':''}</div><h3>${esc(r.name)}</h3><div class="sub">${esc(r.city)} · ${r.distance} km · ${r.elev} D+</div></div><button class="btn ${reg?'secondary':'primary'}" data-register="${r.id}">${reg?'Annuler inscrit':'Je suis inscrit'}</button></div>`}).join(''):'<div class="empty">Aucune course suivie pour le moment.</div>'}
function renderProfile(){nameInput.value=state.profile.name||'';travelRange.value=state.profile.maxTravel||90;travelLabel.textContent=(state.profile.maxTravel||90)+' min';indexSelect.value=state.profile.indexPref||'prefer';locationText.textContent=state.profile.lat==null?'Position non définie. La géolocalisation reste sur ton appareil.':`Position enregistrée (${state.profile.lat.toFixed(3)}, ${state.profile.lon.toFixed(3)}).`}
function renderAll(){renderSeason();renderExplore();renderWatch();renderProfile();save()}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#'+v+'View').classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.go===v));window.scrollTo({top:0,behavior:'smooth'});if(v==='explore')renderExplore();if(v==='watch')renderWatch()}
function openGoal(id){const g=id?state.goals.find(x=>x.id===id):null;goalId.value=g?.id||'';goalType.value=g?.type||'Trail';goalMonth.value=g?.month??activeMonth;goalMin.value=g?.min??20;goalMax.value=g?.max??35;goalWindow.value=g?.window||'month';goalTravel.value=g?.travel||state.profile.maxTravel||90;goalIndex.value=g?.index||state.profile.indexPref||'prefer';goalPriority.value=g?.priority||'normal';goalTitle.textContent=g?'Modifier l’objectif':'Ajouter un objectif';goalDialog.showModal()}
function raceDetailOpen(id){const r=allRaces().find(x=>x.id===id);if(!r)return;const t=travel(r),st=openStatus(r),f=state.following.includes(id),reg=state.registered.includes(id);raceDetail.innerHTML=`<div class="modal-head"><div></div><button class="x" data-close>×</button></div><div class="detail-hero" style="background-image:url('${r.img||IMG[1]}')"><span class="badge">${r.type==='trail'?'Trail':'Route'}</span>${r.index?` <span class="badge index">Index ${r.index}</span>`:''}<h2>${esc(r.name)}</h2><p>${esc(r.city)} · ${new Date(r.date+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</p></div><div class="detail-grid"><div class="kpi"><b>${r.distance} km</b><small>Distance</small></div><div class="kpi"><b>${r.elev} m</b><small>D+</small></div><div class="kpi"><b>${matchRace(r)}%</b><small>Match</small></div><div class="kpi"><b>${t?t.min+' min':'—'}</b><small>Trajet estimé</small></div></div><div class="detail-note"><b>${st.txt}</b><br>Les informations du catalogue bêta servent à tester l’application et doivent être vérifiées sur le site officiel de la course avant inscription.</div><div class="profile-actions"><button class="btn ${f?'secondary':'primary'}" data-follow="${id}">${f?'Retirer de la veille':'Suivre la course'}</button><button class="btn ${reg?'secondary':'outline'}" data-register="${id}">${reg?'Inscrit ✓':'Marquer inscrit'}</button></div>`;raceDialog.showModal()}
MONTHS.forEach((m,i)=>goalMonth.insertAdjacentHTML('beforeend',`<option value="${i}">${m}</option>`));
document.addEventListener('click',e=>{const goEl=e.target.closest('[data-go]');if(goEl)go(goEl.dataset.go);const m=e.target.closest('[data-month]');if(m){activeMonth=+m.dataset.month;renderMonths();const g=state.goals.find(x=>+x.month===activeMonth);if(g)openGoal(g.id);else openGoal()}const add=e.target.closest('[data-add-goal]');if(add)openGoal();const edit=e.target.closest('[data-edit-goal]');if(edit)openGoal(edit.dataset.editGoal);const race=e.target.closest('[data-race]');if(race&&!e.target.closest('[data-follow],[data-register]'))raceDetailOpen(race.dataset.race);const fol=e.target.closest('[data-follow]');if(fol){e.stopPropagation();const id=fol.dataset.follow;state.following=state.following.includes(id)?state.following.filter(x=>x!==id):[...state.following,id];renderAll();if(raceDialog.open)raceDetailOpen(id);toast(state.following.includes(id)?'Course ajoutée à la veille':'Course retirée de la veille')}const reg=e.target.closest('[data-register]');if(reg){e.stopPropagation();const id=reg.dataset.register;state.registered=state.registered.includes(id)?state.registered.filter(x=>x!==id):[...state.registered,id];renderAll();if(raceDialog.open)raceDetailOpen(id);toast(state.registered.includes(id)?'Bravo, course marquée inscrite !':'Statut inscription retiré')}if(e.target.closest('[data-close]'))e.target.closest('dialog').close()});
goalForm.addEventListener('submit',e=>{e.preventDefault();const o={id:goalId.value||'g'+Date.now(),type:goalType.value,month:+goalMonth.value,min:+goalMin.value,max:+goalMax.value,window:goalWindow.value,travel:+goalTravel.value,index:goalIndex.value,priority:goalPriority.value};if(o.priority==='main')state.goals=state.goals.map(g=>({...g,priority:'normal'}));const i=state.goals.findIndex(g=>g.id===o.id);if(i>=0)state.goals[i]=o;else state.goals.push(o);goalDialog.close();renderAll();toast('Objectif enregistré')});
searchInput.addEventListener('input',renderExplore);chips.addEventListener('click',e=>{const c=e.target.closest('.chip');if(!c)return;filter=c.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===c));renderExplore()});customRaceBtn.onclick=()=>customDialog.showModal();customForm.onsubmit=e=>{e.preventDefault();state.customRaces.push({id:'c'+Date.now(),name:crName.value,city:crCity.value,date:crDate.value,type:crType.value,distance:+crDistance.value,elev:+crElev.value,index:crIndex.value,open:crOpen.value||'',lat:null,lon:null,img:IMG[Math.floor(Math.random()*IMG.length)]});customDialog.close();customForm.reset();renderAll();toast('Course ajoutée à ton catalogue')};
nameInput.oninput=()=>{state.profile.name=nameInput.value;save()};travelRange.oninput=()=>{state.profile.maxTravel=+travelRange.value;travelLabel.textContent=travelRange.value+' min';save();renderExplore()};indexSelect.onchange=()=>{state.profile.indexPref=indexSelect.value;save()};geoBtn.onclick=()=>{if(!navigator.geolocation)return toast('Géolocalisation non disponible');geoBtn.textContent='Localisation…';navigator.geolocation.getCurrentPosition(p=>{state.profile.lat=p.coords.latitude;state.profile.lon=p.coords.longitude;geoBtn.textContent='Mettre à jour ma position';renderAll();toast('Position enregistrée')},()=>{geoBtn.textContent='Utiliser ma position';toast('Position refusée ou indisponible')},{enableHighAccuracy:false,timeout:8000})};
shareBtn.onclick=async()=>{const data={title:'TopoSeason Beta',text:'Teste TopoSeason et dis-moi ce que tu en penses.',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Lien copié')}}catch(e){}};
notifBtn.onclick=async()=>{if(!('Notification'in window))return toast('Notifications non disponibles');const p=await Notification.requestPermission();if(p==='granted'){new Notification('TopoSeason',{body:'Notifications locales activées pour le test.'});toast('Notification test envoyée')}else toast('Notifications refusées')};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='toposeason-'+Date.now()+'.json';a.click();URL.revokeObjectURL(a.href);toast('Données exportées')};importBtn.onclick=()=>importFile.click();importFile.onchange=async()=>{try{const x=JSON.parse(await importFile.files[0].text());state={...structuredClone(defaults),...x};renderAll();toast('Données importées')}catch(e){toast('Fichier non reconnu')}};resetBtn.onclick=()=>{if(confirm('Réinitialiser toutes les données locales TopoSeason ?')){state=structuredClone(defaults);renderAll();toast('Données réinitialisées')}};feedbackBtn.onclick=()=>feedbackDialog.showModal();feedbackForm.onsubmit=async e=>{e.preventDefault();const item={date:new Date().toISOString(),rating:+fbRating.value,text:fbText.value};state.feedback.push(item);save();feedbackDialog.close();const txt=`Feedback TopoSeason : ${item.rating}/5\n${item.text||'(sans commentaire)'}`;try{if(navigator.share)await navigator.share({title:'Feedback TopoSeason',text:txt});else{await navigator.clipboard.writeText(txt);toast('Feedback copié, envoie-le à Éric')}}catch(e){}fbText.value=''};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));renderAll();