(() => {
'use strict';
const STORE='toposeason-training-v1',MAXSPD=12,MINMOVE=3,MAXACC=60,ALTSTEP=3;
let data=load(),run=fresh(),watchId=null,timerId=null,wakeLock=null;
function fresh(){return{active:false,paused:false,startedAt:0,pausedAt:0,pausedMs:0,name:'',type:'trail',distanceM:0,ascentM:0,descentM:0,currentSpeed:0,avgSpeed:0,maxSpeed:0,altitude:null,accuracy:null,lastPoint:null,points:[],gpsFixes:0,wake:false}}
function load(){try{return{sessions:[],...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return{sessions:[]}}}
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function note(m){if(typeof toast==='function')toast(m)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function hav(a,b){const R=6371000,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,q=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function elapsed(){if(!run.startedAt)return 0;const end=run.paused?run.pausedAt:Date.now();return Math.max(0,end-run.startedAt-run.pausedMs)}
function hms(ms){const t=Math.floor(ms/1000),h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function pace(km,ms){if(km<.05||ms<1000)return'—';let x=(ms/1000)/km,m=Math.floor(x/60),s=Math.round(x%60);if(s===60){m++;s=0}return`${m}:${String(s).padStart(2,'0')}/km`}
function kmh(mps){return Math.max(0,mps||0)*3.6}
function livePace(){const v=kmh(run.currentSpeed);if(v<1)return'—';let x=60/v,m=Math.floor(x),s=Math.round((x-m)*60);if(s===60){m++;s=0}return`${m}:${String(s).padStart(2,'0')}/km`}
function dateFr(iso){return new Date(iso).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function inject(){if(document.querySelector('#trainingRoot'))return;const top=document.querySelector('.topbar'),mode=document.createElement('div');mode.className='mode-switch-wrap';mode.innerHTML='<div class="mode-switch"><button class="mode-btn active" data-mode="planning">Planification</button><button class="mode-btn" data-mode="training">Entraînement</button></div>';top.insertAdjacentElement('afterend',mode);const root=document.createElement('section');root.id='trainingRoot';root.className='training-root';root.innerHTML='<div id="trainingHome"></div><div id="trainingLive" class="training-live" hidden></div>';document.querySelector('.app').insertBefore(root,document.querySelector('.bottomnav'));
const manual=document.createElement('dialog');manual.id='manualTrainingDialog';manual.innerHTML=`<form class="modal training-form" id="manualTrainingForm"><div class="modal-head"><div><span class="eyebrow">Ajouter une sortie</span><h2>Entraînement manuel</h2></div><button type="button" class="x" data-training-close>×</button></div><div class="formgrid"><div class="field"><label>Nom du parcours</label><input id="mtName" placeholder="Ex. Boucle forêt"></div><div class="field"><label>Date</label><input id="mtDate" type="date" required></div><div class="field"><label>Type</label><select id="mtType"><option value="trail">Trail</option><option value="road">Route</option></select></div><div class="field"><label>Distance (km)</label><input id="mtDistance" type="number" min="0.1" step="0.01" required></div><div class="field"><label>D+ (m)</label><input id="mtAscent" type="number" min="0" value="0"></div><div class="field"><label>Vitesse max (km/h)</label><input id="mtMaxSpeed" type="number" min="0" step="0.1" placeholder="Optionnel"></div></div><div class="duration-fields"><label>Temps</label><div><input id="mtHours" type="number" min="0" value="0"><span>h</span><input id="mtMinutes" type="number" min="0" max="59" value="45"><span>min</span><input id="mtSeconds" type="number" min="0" max="59" value="0"><span>s</span></div></div><button class="btn primary" type="submit">Enregistrer la sortie</button></form>`;document.body.appendChild(manual);
const finish=document.createElement('dialog');finish.id='finishTrainingDialog';finish.innerHTML=`<form class="modal training-form" id="finishTrainingForm"><div class="modal-head"><div><span class="eyebrow">Session terminée</span><h2>Enregistrer l'entraînement</h2></div><button type="button" class="x" data-training-close>×</button></div><div class="finish-summary" id="finishSummary"></div><div class="formgrid"><div class="field"><label>Nom du parcours</label><input id="ftName" placeholder="Sortie sans nom"></div><div class="field"><label>Type</label><select id="ftType"><option value="trail">Trail</option><option value="road">Route</option></select></div><div class="field"><label>Distance corrigée (km)</label><input id="ftDistance" type="number" min="0" step="0.01"></div><div class="field"><label>D+ corrigé (m)</label><input id="ftAscent" type="number" min="0"></div></div><p class="training-hint">Distance et D+ GPS peuvent être corrigés avant sauvegarde.</p><button class="btn primary" type="submit">Sauvegarder</button><button class="btn outline discard-run" type="button" id="discardRunBtn">Ne pas enregistrer</button></form>`;document.body.appendChild(finish);bind();renderHome()}
function bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));document.addEventListener('click',e=>{const c=e.target.closest('[data-training-close]');if(c)c.closest('dialog').close();const d=e.target.closest('[data-delete-session]');if(d)del(d.dataset.deleteSession);if(e.target.closest('#trainingExportBtn'))exportData()});manualTrainingForm.onsubmit=saveManual;finishTrainingForm.onsubmit=saveFinished;discardRunBtn.onclick=()=>{finishTrainingDialog.close();reset();renderHome()};document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&run.active&&!run.paused)wake()})}
function switchMode(m){if(m==='planning'&&run.active&&!confirm('Une session est en cours. Revenir à la planification sans l’arrêter ?'))return;document.querySelectorAll('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));document.body.classList.toggle('training-mode-active',m==='training');if(m==='training')renderHome()}
function renderHome(){const e=document.querySelector('#trainingHome');if(!e)return;const s=[...data.sessions].sort((a,b)=>new Date(b.date)-new Date(a.date)),n=new Date(),mo=s.filter(x=>{const d=new Date(x.date);return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}),km=mo.reduce((a,x)=>a+x.distance,0),up=mo.reduce((a,x)=>a+x.ascent,0),ms=mo.reduce((a,x)=>a+x.durationMs,0);e.hidden=false;trainingLive.hidden=true;e.innerHTML=`<div class="training-head"><span class="eyebrow">TopoSeason Training</span><h1>Pars courir.<br><span>On garde la trace.</span></h1><p>GPS en direct ou saisie manuelle. Les entraînements restent sur ton appareil.</p></div><div class="training-start-card"><div class="training-start-top"><div><span class="live-dot"></span><b>Nouvelle session</b><small>Distance, allure, vitesse, D+ et trace GPS</small></div><span class="gps-pill">GPS téléphone</span></div><div class="start-fields"><input id="liveRunName" placeholder="Nom du parcours (optionnel)"><select id="liveRunType"><option value="trail">Trail</option><option value="road">Route</option></select></div><button class="start-run-btn" id="startRunBtn"><span>▶</span><div><b>Démarrer l'entraînement</b><small>Autoriser la position GPS</small></div></button><button class="manual-link" id="manualTrainingBtn">+ Ajouter une sortie manuellement</button></div><div class="training-month"><div class="training-section-head"><div><span class="eyebrow">Ce mois-ci</span><h2>Volume d'entraînement</h2></div><button class="mini-action" id="trainingExportBtn">Exporter</button></div><div class="training-stats"><div><b>${mo.length}</b><span>sorties</span></div><div><b>${km.toFixed(1)}</b><span>km</span></div><div><b>${Math.round(up)}</b><span>D+</span></div><div><b>${hms(ms).slice(0,5)}</b><span>temps</span></div></div></div><div class="training-history"><div class="training-section-head"><div><span class="eyebrow">Journal</span><h2>Dernières sorties</h2></div></div>${s.length?s.slice(0,20).map(cardSession).join(''):'<div class="empty">Aucun entraînement enregistré.</div>'}</div>`;startRunBtn.onclick=startRun;manualTrainingBtn.onclick=()=>{mtDate.value=new Date().toISOString().slice(0,10);manualTrainingDialog.showModal()}}
function cardSession(s){const p=pace(s.distance,s.durationMs),avg=s.durationMs?s.distance/(s.durationMs/3600000):0;return`<article class="training-session"><div class="session-icon">${s.type==='trail'?'△':'↝'}</div><div><div class="session-title"><b>${esc(s.name||'Sortie sans nom')}</b><small>${dateFr(s.date)}</small></div><div class="session-metrics"><span>${s.distance.toFixed(2)} km</span><span>+${Math.round(s.ascent)} m</span><span>${hms(s.durationMs)}</span><span>${p}</span><span>${avg.toFixed(1)} km/h moy.</span>${s.maxSpeed?`<span>${s.maxSpeed.toFixed(1)} km/h max</span>`:''}</div></div><button class="session-delete" data-delete-session="${s.id}">×</button></article>`}
async function startRun(){if(!navigator.geolocation)return note('GPS non disponible');run=fresh();run.active=true;run.startedAt=Date.now();run.name=(liveRunName.value||'').trim();run.type=liveRunType.value;trainingHome.hidden=true;trainingLive.hidden=false;renderLive();timerId=setInterval(renderMetrics,1000);await wake();watchId=navigator.geolocation.watchPosition(onPos,onErr,{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
async function wake(){if(!('wakeLock'in navigator)||!run.active||run.paused)return;try{wakeLock=await navigator.wakeLock.request('screen');run.wake=true;renderMetrics();wakeLock.addEventListener('release',()=>{run.wake=false;renderMetrics()})}catch{run.wake=false}}
async function releaseWake(){try{if(wakeLock)await wakeLock.release()}catch{}wakeLock=null;run.wake=false}
function onPos(pos){if(!run.active||run.paused)return;const c=pos.coords,t=pos.timestamp||Date.now();run.accuracy=Number.isFinite(c.accuracy)?Math.round(c.accuracy):null;run.altitude=Number.isFinite(c.altitude)?c.altitude:null;if(c.accuracy>MAXACC)return renderMetrics();const p={lat:c.latitude,lon:c.longitude,alt:Number.isFinite(c.altitude)?c.altitude:null,t,acc:c.accuracy};if(run.lastPoint){const d=hav(run.lastPoint,p),dt=Math.max(.5,(p.t-run.lastPoint.t)/1000),derived=d/dt;let sp=Number.isFinite(c.speed)&&c.speed>=0?c.speed:derived;if(sp<=MAXSPD){if(d>=MINMOVE){run.distanceM+=d;if(p.alt!=null&&run.lastPoint.alt!=null){const da=p.alt-run.lastPoint.alt;if(da>=ALTSTEP)run.ascentM+=da;else if(da<=-ALTSTEP)run.descentM+=-da}run.points.push(p)}run.currentSpeed=run.gpsFixes?run.currentSpeed*.65+sp*.35:sp;if(sp>run.maxSpeed)run.maxSpeed=sp}}else run.points.push(p);run.lastPoint=p;run.gpsFixes++;run.avgSpeed=elapsed()?(run.distanceM/1000)/(elapsed()/3600000):0;renderMetrics();drawRoute()}
function onErr(e){set('gpsState',({1:'Autorisation GPS refusée',2:'Position GPS indisponible',3:'Recherche GPS trop longue'})[e.code]||'GPS indisponible')}
function renderLive(){trainingLive.innerHTML=`<div class="live-top"><div><span class="live-dot"></span><b>COURSE ACTIVE</b><small id="gpsState">Acquisition GPS…</small></div><div class="live-name">${esc(run.name||'Entraînement libre')}</div></div><div class="live-speed-block"><span>Vitesse</span><b id="liveSpeed">0.0</b><em> km/h</em><small id="livePace">—</small></div><div class="live-primary"><div><span>Temps</span><b id="liveTime">00:00:00</b></div><div><span>Distance</span><b id="liveDistance">0.00 km</b></div><div><span>Allure moy.</span><b id="liveAvgPace">—</b></div></div><div class="route-panel"><div class="route-head"><span>Trace GPS</span><small id="gpsAccuracy">Précision —</small></div><svg id="routeSvg" viewBox="0 0 320 130" preserveAspectRatio="none"><polyline id="routeLine" points=""/></svg></div><div class="live-secondary"><div><span>Vitesse moy.</span><b id="liveAvgSpeed">0.0 km/h</b></div><div><span>Vitesse max GPS</span><b id="liveMaxSpeed">0.0 km/h</b></div><div><span>D+</span><b id="liveAscent">0 m</b></div><div><span>Altitude</span><b id="liveAltitude">—</b></div></div><div class="gps-note"><span id="wakeState">Écran actif</span><span>Vitesse max et D+ peuvent varier selon la précision GPS.</span></div><div class="live-controls"><button id="pauseRunBtn" class="live-control pause">Ⅱ <span>Pause</span></button><button id="finishRunBtn" class="live-control finish">■ <span>Terminer</span></button></div>`;pauseRunBtn.onclick=pause;finishRunBtn.onclick=finish;renderMetrics()}
function renderMetrics(){if(!run.active)return;const ms=elapsed(),km=run.distanceM/1000;set('liveTime',hms(ms));set('liveDistance',km.toFixed(2)+' km');set('liveSpeed',kmh(run.currentSpeed).toFixed(1));set('livePace',livePace());set('liveAvgPace',pace(km,ms));set('liveAvgSpeed',run.avgSpeed.toFixed(1)+' km/h');set('liveMaxSpeed',kmh(run.maxSpeed).toFixed(1)+' km/h');set('liveAscent',Math.round(run.ascentM)+' m');set('liveAltitude',run.altitude==null?'—':Math.round(run.altitude)+' m');set('gpsAccuracy',run.accuracy==null?'Précision —':`Précision ±${run.accuracy} m`);set('gpsState',run.paused?'Session en pause':run.gpsFixes?'GPS actif':'Acquisition GPS…');set('wakeState',run.wake?'Écran maintenu actif':'Garde l’écran ouvert')}
function drawRoute(){const l=document.querySelector('#routeLine');if(!l||run.points.length<2){if(l)l.setAttribute('points','');return}const pts=run.points,la=pts.map(p=>p.lat),lo=pts.map(p=>p.lon),a=Math.min(...la),b=Math.max(...la),c=Math.min(...lo),d=Math.max(...lo),dx=Math.max(.00001,d-c),dy=Math.max(.00001,b-a),pad=10,out=pts.filter((_,i)=>i%Math.max(1,Math.floor(pts.length/180))===0).map(p=>`${(pad+(p.lon-c)/dx*(320-pad*2)).toFixed(1)},${(130-pad-(p.lat-a)/dy*(130-pad*2)).toFixed(1)}`).join(' ');l.setAttribute('points',out)}
function pause(){if(!run.paused){run.paused=true;run.pausedAt=Date.now();run.currentSpeed=0;releaseWake()}else{run.paused=false;run.pausedMs+=Date.now()-run.pausedAt;run.pausedAt=0;run.lastPoint=null;wake()}pauseRunBtn.innerHTML=run.paused?'▶ <span>Reprendre</span>':'Ⅱ <span>Pause</span>';renderMetrics()}
function finish(){if(!confirm('Terminer cette session ?'))return;if(watchId!=null)navigator.geolocation.clearWatch(watchId);watchId=null;if(timerId)clearInterval(timerId);timerId=null;releaseWake();run.active=false;const ms=elapsed(),km=run.distanceM/1000;finishSummary.innerHTML=`<div><b>${km.toFixed(2)}</b><span>km</span></div><div><b>${hms(ms)}</b><span>temps</span></div><div><b>${pace(km,ms)}</b><span>allure</span></div><div><b>${kmh(run.maxSpeed).toFixed(1)}</b><span>km/h max</span></div>`;ftName.value=run.name;ftType.value=run.type;ftDistance.value=km.toFixed(2);ftAscent.value=Math.round(run.ascentM);finishTrainingDialog.showModal()}
function saveFinished(e){e.preventDefault();data.sessions.push({id:'t'+Date.now(),date:new Date().toISOString(),name:ftName.value.trim()||'Sortie sans nom',type:ftType.value,distance:+ftDistance.value||0,ascent:+ftAscent.value||0,descent:Math.round(run.descentM),durationMs:elapsed(),maxSpeed:kmh(run.maxSpeed),source:'gps',points:run.points.length});save();finishTrainingDialog.close();reset();renderHome();note('Entraînement sauvegardé')}
function saveManual(e){e.preventDefault();const ms=((+mtHours.value||0)*3600+(+mtMinutes.value||0)*60+(+mtSeconds.value||0))*1000;if(ms<=0)return note('Renseigne un temps');data.sessions.push({id:'t'+Date.now(),date:new Date(mtDate.value+'T12:00:00').toISOString(),name:mtName.value.trim()||'Sortie sans nom',type:mtType.value,distance:+mtDistance.value||0,ascent:+mtAscent.value||0,descent:0,durationMs:ms,maxSpeed:+mtMaxSpeed.value||0,source:'manual',points:0});save();manualTrainingDialog.close();e.target.reset();renderHome();note('Sortie ajoutée')}
function del(id){if(!confirm('Supprimer cet entraînement ?'))return;data.sessions=data.sessions.filter(s=>s.id!==id);save();renderHome()}
function reset(){if(watchId!=null)navigator.geolocation.clearWatch(watchId);if(timerId)clearInterval(timerId);watchId=null;timerId=null;releaseWake();run=fresh();trainingLive.hidden=true;trainingHome.hidden=false}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='toposeason-entrainements-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();